# Instagram Likes Data Report
## William Adams 
## 9/16/2026
I unfortunately do not have an account on either Instagram or Facebook, so the source of my data comes from my teacher's Instagram account. <br>
This data was created by Instagram in order to keep track of the likes applied by this account in order to personalize their experience in the app. <br>
This data may be reliable because it comes directly from Instagram itself. <br>
This data may be unreliable because there exists certain aspects of the data that are not provided here. <br>

In [1]:
import json
import pandas as pd

with open("liked_posts.json", "r") as f:
    data = json.load(f)

data[0]

{'timestamp': 1788114943,
 'media': [],
 'label_values': [{'label': 'URL',
   'value': 'https://www.instagram.com/p/DcrKLiNCV5F0jhQ2_0QFnlDamOwbYfoZVfzs8s0/',
   'href': 'https://www.instagram.com/p/DcrKLiNCV5F0jhQ2_0QFnlDamOwbYfoZVfzs8s0/'},
  {'label': 'Caption', 'value': 'Smiling because itâ\x80\x99s Sunday!'},
  {'label': 'Title', 'value': ''},
  {'dict': [], 'title': 'Hashtags'},
  {'dict': [{'dict': [{'label': 'URL', 'value': ''},
      {'label': 'Name', 'value': 'Sophie Peerless'},
      {'label': 'Username', 'value': 'sophie_peerless08'}],
     'title': ''}],
   'title': 'Owner'},
  {'dict': [], 'title': 'Brand partner'}],
 'fbid': '18037111067834578'}

In [3]:
row = {}
row['timestamp'] = data[0]['timestamp']

row

{'timestamp': 1788114943}

In [4]:
for item in data[0]['label_values']:
    if 'label' in item:
        row[item['label']] = item['value']

row

{'timestamp': 1788114943,
 'URL': 'https://www.instagram.com/p/DcrKLiNCV5F0jhQ2_0QFnlDamOwbYfoZVfzs8s0/',
 'Caption': 'Smiling because itâ\x80\x99s Sunday!',
 'Title': ''}

In [5]:
for item in data[0]['label_values']:
    if 'label' in item:
        row[item['label']] = item['value']
    elif item.get('title') == 'Owner':
        owner_fields = item['dict'][0]['dict']
        for owner_item in owner_fields:
            row['Owner ' + owner_item['label']] = owner_item['value']

row

{'timestamp': 1788114943,
 'URL': 'https://www.instagram.com/p/DcrKLiNCV5F0jhQ2_0QFnlDamOwbYfoZVfzs8s0/',
 'Caption': 'Smiling because itâ\x80\x99s Sunday!',
 'Title': '',
 'Owner URL': '',
 'Owner Name': 'Sophie Peerless',
 'Owner Username': 'sophie_peerless08'}

In [6]:
tidy_rows = []

for entry in data:
    row = {}
    row['timestamp'] = entry['timestamp']
    
    for item in entry['label_values']:
        if 'label' in item:
            row[item['label']] = item['value']
        elif item.get('title') == 'Owner':
            owner_fields = item['dict'][0]['dict']
            for owner_item in owner_fields:
                row['Owner ' + owner_item['label']] = owner_item['value']
    tidy_rows.append(row)

tidy_rows[:2]

[{'timestamp': 1788114943,
  'URL': 'https://www.instagram.com/p/DcrKLiNCV5F0jhQ2_0QFnlDamOwbYfoZVfzs8s0/',
  'Caption': 'Smiling because itâ\x80\x99s Sunday!',
  'Title': '',
  'Owner URL': '',
  'Owner Name': 'Sophie Peerless',
  'Owner Username': 'sophie_peerless08'},
 {'timestamp': 1788086270,
  'URL': 'https://www.instagram.com/p/Dcn-TKdDjwY/',
  'Caption': 'What a great night for our Par 3 Food Truck event! Capped off by a 9 Hole Putting contest under the lights. \n\n- Hole In One Alert on #8ð\x9f\x9a¨ Kelley Mehallis -',
  'Title': '',
  'Owner URL': 'https://charity.pledgeit.org/c/B4QRc389rO',
  'Owner Name': 'Walden Golf Shop',
  'Owner Username': 'waldengolfshop'}]

My teacher has mentioned several hobbies of hers, the two most prominant being fight robots and golfing. I would like to see if there is evidence of these activities in her Instagram data, as well as if there is evidence of her job as a teacher at Kent State.

I believe that the columns that I have chosen will allow me to answer this question, as the caption and owner name/username will include data that will allow me to see what the post, or account that made said post, is about. I will be sorting the data by date and taking the ten most recent posts, as the posts that are most recent are also likely to provide the most accurate view of the user and their account.

In [7]:
likes_df = pd.DataFrame(tidy_rows)
likes_df.head(10)

,timestamp,URL,Caption,Title,Owner URL,Owner Name,Owner Username
0,1788114943,https://www.instagram.com/p/DcrKLiNCV5F0jhQ2_0...,Smiling because itâs Sunday!,,,Sophie Peerless,sophie_peerless08
1,1788086270,https://www.instagram.com/p/Dcn-TKdDjwY/,What a great night for our Par 3 Food Truck ev...,,https://charity.pledgeit.org/c/B4QRc389rO,Walden Golf Shop,waldengolfshop
2,1788057327,https://www.instagram.com/p/DcoUHKKDn2p/,Some photos from last nightâs Couples Twilig...,,http://www.portagecc.org/,Portage Country Club,portagecountryclub
3,1788056601,https://www.instagram.com/p/DcpQPLzgJbn/,Great day at Buckeye Bot Bash 2 today! I canâ...,,,Nathan Milhorn,8snoman8
4,1787952264,https://www.instagram.com/p/DcmQ-5NIhcH/,"á´á´É´á´, Éªá´âê± ê°ÊÉªá´ á´Ê.\ná´...",,,Beware of The Leopard Kent,bewareoftheleopardkent
5,1787947692,https://www.instagram.com/p/DcmKrwOgAIi/,Feeling like I should call this colorâMaple ...,,http://www.goodcosalon.com/,Erica Evans,ericaevans.hair
6,1787933042,https://www.instagram.com/p/Dcloqx1DrLA/,"Surgeons, engineers, teachers and more! ð¤ T...",,,United States Golf Association,usga
7,1787927416,https://www.instagram.com/p/DckBC_4uqKG/,Thursday Night Football by the lake. #gobrowns...,,,Jared Simon,jaredlsimon
8,1787922955,https://www.instagram.com/p/DclZAPFlr26/,Informational Meeting tonight! \nAugust 28th @...,,https://popup.doublegood.com/s/ts8r17c0,Kent State Vex Robotics Team,kent_state_robotics_team
9,1787920432,https://www.instagram.com/p/DclXFbzuIUeSPcRzLf...,Woodrow Jacques. Born August 23rd 2026. ð,,,jocelyn,jcbonn

In [8]:
likes_df['DateTime'] = pd.to_datetime(likes_df['timestamp'], unit='s')
likes_df[['timestamp', 'DateTime']].head()

    timestamp            DateTime
0  1788114943 2026-08-30 18:35:43
1  1788086270 2026-08-30 10:37:50
2  1788057327 2026-08-30 02:35:27
3  1788056601 2026-08-30 02:23:21
4  1787952264 2026-08-28 21:24:24

One drawback of using this kind of data is seen here; the most recent posts within it are already outdated by several weeks at time of writing. In order to keep it up-to-date, one would need to extract this data from Instagram constantly, which is a very inefficient and time-consuming process.

In [17]:
likes_df.head(10)

,timestamp,URL,Caption,Title,Owner URL,Owner Name,Owner Username
0,1788114943,https://www.instagram.com/p/DcrKLiNCV5F0jhQ2_0...,Smiling because itâs Sunday!,,,Sophie Peerless,sophie_peerless08
1,1788086270,https://www.instagram.com/p/Dcn-TKdDjwY/,What a great night for our Par 3 Food Truck ev...,,https://charity.pledgeit.org/c/B4QRc389rO,Walden Golf Shop,waldengolfshop
2,1788057327,https://www.instagram.com/p/DcoUHKKDn2p/,Some photos from last nightâs Couples Twilig...,,http://www.portagecc.org/,Portage Country Club,portagecountryclub
3,1788056601,https://www.instagram.com/p/DcpQPLzgJbn/,Great day at Buckeye Bot Bash 2 today! I canâ...,,,Nathan Milhorn,8snoman8
4,1787952264,https://www.instagram.com/p/DcmQ-5NIhcH/,"á´á´É´á´, Éªá´âê± ê°ÊÉªá´ á´Ê.\ná´...",,,Beware of The Leopard Kent,bewareoftheleopardkent
5,1787947692,https://www.instagram.com/p/DcmKrwOgAIi/,Feeling like I should call this colorâMaple ...,,http://www.goodcosalon.com/,Erica Evans,ericaevans.hair
6,1787933042,https://www.instagram.com/p/Dcloqx1DrLA/,"Surgeons, engineers, teachers and more! ð¤ T...",,,United States Golf Association,usga
7,1787927416,https://www.instagram.com/p/DckBC_4uqKG/,Thursday Night Football by the lake. #gobrowns...,,,Jared Simon,jaredlsimon
8,1787922955,https://www.instagram.com/p/DclZAPFlr26/,Informational Meeting tonight! \nAugust 28th @...,,https://popup.doublegood.com/s/ts8r17c0,Kent State Vex Robotics Team,kent_state_robotics_team
9,1787920432,https://www.instagram.com/p/DclXFbzuIUeSPcRzLf...,Woodrow Jacques. Born August 23rd 2026. ð,,,jocelyn,jcbonn

In this table, I can see several pieces of data that confirm my hypothesis. There is one post from both the Walden Golf Shop and one from the United States Golf Association, giving evidence that the user is a golfer. There is also one messsage from the Kent State Vex Robotics Team, and a different message whose caption mentions the Buckeye Bot Bash 2, giving evidence that the user enjoys robot fighting. Several posts contain references to Kent State and the surrounding area, although none of them could be used to infer that the user is specifically a teacher at Kent State, which exemplifies the drawbacks of this data.

I believe that this data is in a tidy and easy-to-understand format, which contains all of the information that is needed to test my hypothesis.